### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by kcalvinalvin** [theuni/libutreexo#1]
I'd be happy to take over the project but the utreexo lib is changing a bit here and there so not sure if it's the right time to go about it?

**Comment by theuni** [comment]
Sorry for missing this years ago. I see you have a fork here https://github.com/kcalvinalvin/libutreexo and I learned today that @dergoegge has one here: https://github.com/dergoegge/libutreexo

It seems there's been at least some utility from this repo, so I'm going to call that a success!

I'll update the descriptions to indicate that this repo is deprecated and point to the others. If one is more canonical at this point than the other, please let me know and I'll make that clear.

Thanks to those who have done the actual work on this!

Edit: whoops, hit send to quickly!

**Comment by dergoegge** [comment]
@theuni https://github.com/mit-dci/libutreexo is currently the most canonical.

**Comment by theuni** [comment]
Thank. I'll update and archive the repo.
